gen.PROJECT_URL=/Users/garellano/development/code/generator/
gen.SOURCE_URL=src/main/java/com/cinepolis/plank-back/

gen.AUTOR=Gustavo A. Arellano
gen.VERSION=1.0-SNAPSHOT
gen.NOMBRE_PROYECTO=proyecto

gen.PACKAGE_BASE=mx.qbits.unam.proyecto.api

gen.DEFINITION_FOLDER=/Users/garellano/Desktop/generator-workspace/definitions/
gen.TARGET_DIR=/Users/garellano/Desktop/generator-workspace/out2/
gen.TEMPLATES_DIR=/Users/garellano/Desktop/generator-workspace/

