gen.PROJECT_URL=/Users/garellano/Desktop/petstore-back/generator/
gen.SOURCE_URL=src/main/java/io/kebblar/petstore/

gen.AUTOR=Fhernanda Romo
gen.VERSION=1.0-SNAPSHOT
gen.NOMBRE_PROYECTO=petstore

gen.PACKAGE_BASE=io.kebblar.petstore.api

gen.DEFINITION_FOLDER=/home/fher/Desktop/generator-workspace/definitions/
       gen.TARGET_DIR=/home/fher/Desktop/generator-workspace/out2/
    gen.TEMPLATES_DIR=/home/fher/Desktop/generator-workspace/

